comment:
  image:
    repository: paradoxalien/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: paradoxalien/post
    tag: latest
  service:
    externalPort: 5000

ui:
  image:
    repository: paradoxalien/ui
    tag: latest
  service:
    externalPort: 9292
