version: '3.3'
services:
  post_db:
    env_file: .env
    image: mongo:${MONGO_VER}
    volumes:
      - post_db:/data/db
    networks:
      reddit:
        aliases:
          - post_db
          - comment_db
  ui:
    env_file: .env
   # build: ./ui
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      - ${EXT_PORT}:${INT_PORT}/tcp
    networks:
      - reddit
  post:
    env_file: .env
   # build: ./post-py
    image: ${USERNAME}/post:${POST_VER}
    networks:
      - reddit
  comment:
    env_file: .env
   # build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VER}
    networks:
      - reddit
  prometheus:
    env_file: .env
    image: ${USERNAME}/prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
    command:
    # Передаем доп параметры вкомандной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - reddit

volumes:
  post_db:
  prometheus_data:

networks:
  reddit:
