version: '3.3'
services:
  post_db:
    image: mongo:${MOGO_VER}
    volumes:
      - post_db:/data/db
    networks:
      - reddit
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      - ${EXT_PORT}:${INT_PORT}/tcp
    networks:
      - reddit
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VER}
    networks:
      - reddit
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VER}
    networks:
      - reddit

volumes:
  post_db:

networks:
  reddit:
